####################################################################################################
# Author: Cuong. Duong Manh <cuongdm8499@gmail.com>
# Description:
#  - This manifest creates a StorageClass using cinder.csi.openstack.org provisioner.
#  - And then create a PersistentVolumeClaim using the above StorageClass.
#  - Finally, create a Deployment nfs-server using the above PersistentVolumeClaim, and expose 
# nfs-server as Service.
####################################################################################################


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-cinderplugin  # [1] The StorageClass name, CAN be changed
provisioner: cinder.csi.openstack.org
parameters:
  type: 7816bad1-7f5b-4400-b2fd-b6334dc32d4b
allowVolumeExpansion: true
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-cinderplugin  # [2] The PersistentVolumeClaim name, CAN be changed
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # [3] The volume size, CAN be changed
  storageClassName: csi-sc-cinderplugin  # MUST be same value with [1]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server  # [7] The Deployment name, CAN be changed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server  # MUST be same value with [6]
  template:
    metadata:
      labels:
        app: nfs-server  # [6] The app label, CAN be changed
    spec:
      containers:
      - name: nfs-server
        image: registry.vngcloud.vn/public/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports  # [5] The volume mount path, CAN be changed
            name: my-volume-name  # MUST be same value with [4]
      volumes:
      - name: my-volume-name  # [4] The volume mount name, CAN be changed
        persistentVolumeClaim:
          claimName: csi-pvc-cinderplugin  # MUST be same value with [2]
          readOnly: false
---

apiVersion: v1
kind: Service
metadata:
  name: nfs-service  # [8] The Service name, CAN be changed
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server  # MUST be same value with [6]
