####################################################################################################
# Author: Cuong. Duong Manh <cuongdm8499@gmailcom>
# Description:
#   - Create an application deployment with 2 replicas, expose it as a service with type LoadBalancer 
#     using vcontainer-ccm
####################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-http-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: external-http-nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
