apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: vcr.vngcloud.vn/60108-cuongdm3/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name: external-hello-world
  annotations:
    vks.vngcloud.vn/load-balancer-name: external-hello-world
spec:
  selector:
    app: hello-world
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
