# Define the StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinderplugin-sc-5000
parameters:
  type: 5000iops_PUBC06-NVME-01
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cinderplugin-sc-10000
parameters:
  type: 10000iops_PUBC06-NVME-01
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
---

# Define the source PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  storageClassName: csi-cinderplugin-sc-5000
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# Define the cloned PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-clone
spec:
  dataSource:
    name: source-pvc
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinderplugin-sc-10000
---

# Define the Pod that using the cloned PVC
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: csi-data-cinderplugin
  volumes:
  - name: csi-data-cinderplugin
    persistentVolumeClaim:
      claimName: csi-pvc-clone
      readOnly: false
      