##################################################################################################################
# Author: Cuong. Duong Manh <cuongdm3@vng.com.vn>
# Description: Configuration for the VKS cluster
# File: secret.yaml
##################################################################################################################

apiVersion: v1
kind: Secret
data:
  cacert: Cg==
  clouds.yaml: <PUT_YOUR_SECRET_HERE>
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: vks-cluster-cloud-config-secret
  namespace: default
